FROM ubuntu:22.04

RUN apt update -y
RUN apt install -y build-essential python3-dev
RUN apt install -y python3-pip python3-numpy
RUN apt install -y screen curl
WORKDIR /server
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
CMD ["./start_gateway.sh"]

