FROM python:3.12-slim

RUN apt-get update && apt-get install -y screen
WORKDIR /server
COPY requirements.txt.sat .
RUN pip3 install --no-cache-dir -r requirements.txt.sat
COPY . .
CMD ["./start_orb.sh"]
